// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExitApp():Promise<void>;

export function GetImageBase64(arg1:string):Promise<string>;

export function GetImageDimensions(arg1:string):Promise<{[key: string]: number}>;

export function OpenImageDialog():Promise<string>;

export function ResizeWindow(arg1:number,arg2:number):Promise<void>;

export function RestoreWindowSize():Promise<void>;
