// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExitApp() {
  return window['go']['main']['App']['ExitApp']();
}

export function GetImageBase64(arg1) {
  return window['go']['main']['App']['GetImageBase64'](arg1);
}

export function GetImageDimensions(arg1) {
  return window['go']['main']['App']['GetImageDimensions'](arg1);
}

export function OpenImageDialog() {
  return window['go']['main']['App']['OpenImageDialog']();
}

export function ResizeWindow(arg1, arg2) {
  return window['go']['main']['App']['ResizeWindow'](arg1, arg2);
}

export function RestoreWindowSize() {
  return window['go']['main']['App']['RestoreWindowSize']();
}
